---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ../../../database/cloudnative-pg/app/secret.sops.yaml
configMapGenerator:
  - name: mautrix-discord-configmap
    files:
      - config.yaml=./resources/config.yaml
      - double-puppet-registration.yaml=./resources/double-puppet-registration.yaml
      - registration.yaml=./resources/registration.yaml
generatorOptions:
  disableNameSuffixHash: true
