# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-discord-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:MNdTixIaMJyHixL9bDvyjbk7wD8bL8KNgWXyQPYy2BtOcronslIYUg==,iv:MUmwfHmuGy+0UzHkihKj3gnCc2hYsD6VqlDEOgtr+1Y=,tag:suIpZYXxItY5TwH0BI4f4A==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:xcIpvwzIV4C61TYsqo2O,iv:Kb311euwyq7GkYZ7UIs3z5tFGfEDl+zrz4wnUpEX81Y=,tag:xyiVi423K7WcU2lTvi3HZw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:eQRcrHRu5pBvRB0YWceC,iv:g1m8dXBGcz4W7e2V6F8xjWdD6j1QzOhJGKxOKr+oCFk=,tag:kehnQssyy+W8Q+Q1p09C0A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:yK5Mhsp6pU1t1lEO/a4i4M9pt7UnxPrEILy/1dPpD6UEQWE=,iv:5aWpmiA1FbCB+Kq7Qsjy6BSKnntNF1gfYlS5nTTnBis=,tag:aDajnygGpTvS+YgMxkfd/g==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQUFBsaFFRNmNrSWFOcmlx
        ZkF5Lzh6cjlCa1NMOVdRVWJyQnNVcFY1Y1NBClBrVDJHUWJYWmZUZzk4bkVabURT
        YlNuS3NOeWF0MVhzWUxoaXRHSGQza0EKLS0tIEIwZHN1bjR5N2U1N2tGeVdPUlkv
        UmF1S2RqdTd1Zzl3TGFsL2dhWkZMVzgKu0Drdoed7mBV697wTHqNBZZ08lS5sIXG
        PsIcwEPNEmFwJsZTorbhh3J9khaNmVmthfGqN3XGBUjA2W2lDf5sBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T23:03:27Z"
  mac: ENC[AES256_GCM,data:6BT2mL/NSBOZ+VU92kVp1+5PE1LLhps4HoH4Rc61VILag/b3nPK1MoMmMI3dVjwNyaXXz+LmSW1pbWR6pDtnQFjPA6PnYlQX2bd2JYxJD6qHT0sDv3uB8W0OhNgjrKtbgozDBTIhd4igcsN9USd6m6sdsRGXQ1h3edTcAosFs10=,iv:cSEcBhgRWrd8XS2L0LqAxDycIXJUTY+4ybNMJYo5WR0=,tag:t38MhVEYCbtl4qVJRQVo0g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
