# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-discord-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dModzlzlFzgQGtLLwn1K4b3ctAdyeAlLSGGXpN5AHMTqayScvAmt5g==,iv:zMHVqBBYPE1qfD6iYXg01hwzMCYKmL6aotJxIfCiMc0=,tag:otFmAzWVYKHPJL+Z1y6VMw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:VPkNLGdEVtJKjcJQoAfZ,iv:Mcq1Y4BrVcR6RmhocJ4lp7yBVT0naBBhNI4iNSCtyZ4=,tag:pal55bDE/Crcyd8ergYbqw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:5++E0V+65SkBnQfrrFaF,iv:rJi1vc3oQoygh7dIA/ll/BKY7QfGNg3P/TUvs4mxHcs=,tag:dY2c7/maJhsgz9MxIs6fdA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:c3gi47eQSnbWPUDqj/MxvaaAbw/Uec4pHk5ULH4j7U5HUGo=,iv:cJGluC0M9XX8ak7BxlPk7IZ2tbWVHZRkNm0j84PiILM=,tag:0GHNOlPQE7n3y4WGI1yeYw==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qIwkuDly64H6eZIw4gq0TGIi2Rl8Obzhfoqzkw==,iv:LegPm9L1X7BH/DA/vfzZ9NB/yxJa1BFuFX44hrpEC/o=,tag:gCAwoVjDsnfNpUYcz4PP2w==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLZkFOajVrSjNBdXpiYU55
        SFErR0o5MG10TzY5RG56dHk3UzVFcU5NR1V3CjBESVV0SUhKeTNOZ2hpQTgxV21K
        S2F1QkpDcFVCVU9KSUhIbjVybFYvT00KLS0tIFJ1Tktua3dwc3ZQZEV1K2N4NnB5
        MlBkcmRtOS95Q0JmUEpQWWJ0YjFEalUKyszdFqwXqJs52Z+Sc+osR0+mRxSRT0d5
        BCVOEprkhxd0WhXv1ppMtlFCREkSZN47VDXx52zVaVWaJjisJ46I0Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T01:02:14Z"
  mac: ENC[AES256_GCM,data:Rm/7CHaEwB7cXseK6zkaT87+bFurRFuOB/gjXxpZxPgs/tWXCeeyHu/WBbpENHCAhr9f8lBoZiiMsQUw8dK06zVBY0XlJJiMPH3f4+kIV7pYl+R09gpR7uA/E0M74KVSx09YFRKKMi4XDM77GW9uA7WTNQ4seHIcBOpCL6Iqlz8=,iv:YywR6stHw3JI2usKJSNvpZro+BvRqjX4S5ses7DW/Wo=,tag:v2jff1toW72dFWWGJ0JvAQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
