# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-discord-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4tS6YkKYiTjh/4wQUqTUYvJuUmyJ+geezOrqim+h8PBnJou/HMJNWQ==,iv:QmJTpwI9Qp0pgiBVkvjrvMRFgJG7AuM+J7G+BGOCAmY=,tag:6zR58W6i8pmT9i9fZudXVw==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:CiyJXkib1jZVU8uJ7uU0,iv:70Gx/GpgU1so0i0dpBSCNGYDEecI7Nbjyvr8rhtowrQ=,tag:6duhiCTHtngSd2aJnpX7NA==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:+o0Easp+dszlEcywrG8F,iv:ISMgpPLavZRbT8MtVujet/mc0D9ZALO73qzPhQtJ3VI=,tag:zdLcgf7KJRNVXmo99AvIHw==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:A1tAtvnIjV5TN5LRXYW/ZdfeV6BvUDcSD3dvSQphFUygTpw=,iv:V1GSqRwRoMXwUXzfrQIqHSn5VfnBHdP6v061tHWNP0A=,tag:V+v9SqXjwdPKSQBu22T07g==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:4k1v8mmkoK7yAaJfybYbWSwf4Sz/nTeGWdDr2A==,iv:zW4lA3dOa+lS0vNRFtGII7hp0OHEgraPomS/x61+oBs=,tag:iIWBjtmx4I6kcrkNQ/3NEg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVjFYVDRRNVVyRExHRXlF
        Zms1QkY5RndoL0pSbkpBdVFYOUVJMVROcVNvCml6eUxMQUhzT0dZOHFrencrSEVB
        LzJ6N1Brb3hONXlxVkxtcWRvQVEvV2cKLS0tIHByNkEvYndvTWlTbERLSllYdGxy
        VER2bUlSMEpjaVRvR1NHdHhkMkZUcE0KPT+2l2skc5u01Q/GRH/5AfMt8arOSjpr
        ac4RIDklYLyBx9ZCPAXejW8mX2nclBvjHZ+fhJwZTS3C2EhZgPmv1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T00:03:52Z"
  mac: ENC[AES256_GCM,data:5d1KvDx4fOBiSk71WD40DE7bmnUMnJFGCWTuoz1RG6yNtHxNHJNEQHpQZH1CGivroTYBxAkGvpPdPSqGp/0B9eizcb8R60781m4Am3N+Tf6QgPHehxKLdpSPZEHwcSdJxm+U7bUYa5q4vfsRrCF7PjCTA8mMHyY2qIXrQFxfpCo=,iv:KPRJgzYfOynsLtxJREL0wHFtHfWSE6hjnOL9I45mczg=,tag:sK9AASTRzwKG6Tuj07KW9g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
