---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app mautrix-linkedin
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: mautrix-linkedin-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: "mautrix-linkedin-configmap"
            items:
              - key: config.yaml
        - configMap:
            name: "mautrix-linkedin-configmap"
            items:
              - key: registration.yaml
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: "336bff2a-c389-4307-bacc-b3bf016ee8d6"
    - secretKey: MAUTRIX_LINKEDIN_POSTGRES_USER
      remoteRef:
        key: "2d87fefd-c020-444f-8170-b3c40177b410"
    - secretKey: MAUTRIX_LINKEDIN_POSTGRES_PASSWORD
      remoteRef:
        key: "cdfb7319-69bd-45ab-83e5-b3c40177c322"
    - secretKey: MAUTRIX_LINKEDIN_POSTGRES_DB
      remoteRef:
        key: "4e7da649-ad45-4946-a235-b3c40177cdcf"
    - secretKey: LINKEDIN_AS_TOKEN
      remoteRef:
        key: "5d9695df-3dda-4048-b099-b3c40177d908"
    - secretKey: LINKEDIN_HS_TOKEN
      remoteRef:
        key: "fdc63eae-003e-4058-8655-b3c40177e54d"
    - secretKey: LINKEDIN_SENDER_LOCAL_PART
      remoteRef:
        key: "754b01e1-9445-4d8c-b106-b3c40177ee02"
    - secretKey: DISCORD_DOUBLE_PUPPET_AS_TOKEN
      remoteRef:
        key: "0b74846e-7a46-4c0b-866a-b3c0000123ad"
    - secretKey: DISCORD_DOUBLE_PUPPET_HS_TOKEN
      remoteRef:
        key: "5e64a842-2685-4293-86fb-b3c00001e7b1"
    - secretKey: DISCORD_DOUBLE_PUPPET_LOCAL_PART
      remoteRef:
        key: "43979b54-8b8e-4a7f-a8d6-b3c000039d41"
