# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-linkedin-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:QhDwUNsQZmefPspfA6C0skcCBXENSR/HsBO5+ygtCmQGgfccLu5aqg==,iv:DZ59FIVioP8C3dyOaQOSGx+YN0w0adT0r2BoU6ENpxE=,tag:RnwkRBx9lhJshGGeLDy0eg==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:FJJi72EjCcPGJ8aCluSF5Q==,iv:ObCUI0Nzf14of04lgUXFxNNWuEqag9pM7ahsxGSIpSQ=,tag:/4//Yjm4Ii0enO62uxljUw==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZlioMEhypfR4A33yCkjk7g==,iv:yfU4rPEmvKiR1BFjn2HgX87MPCi1BCjPu69FAivpaTg=,tag:46d0pKOh8ToEveJpzYgryg==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8x/dGOmodhoGH9eYGjWVVHcafqsSqYiqID0k34893a9pE/u5NL/LKpMXANzc/CIZIVER69d/CtU=,iv:Vija6fsMhKiofSmsRcVuNa6AcIUYh7eIy/rC5o9GvFs=,tag:W8dG8Oz4CgaPXkkAr+XDbw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRNzVuY1BwTUJsbjBXWUxK
        ZHBqSkNXaFZRZ3RmajhqQlA2RXFuUkZ6OEJjCm16YjE4c3dic2ozVFZ3NlVIOHFu
        VHpmT1VYdjdodzFQQWlLcXgzUlZBQkEKLS0tIFpyY0F2RWZPRUhtVHBwMWVpeHJ2
        ZWlQUWc5RTdjVVZJN3Y2RGZ2bExVM28KrUeLXc55w4Ejdfaedfw6oPtcobA3Ae6F
        rhRqRC55d10ra4bNZu3iX7RckKAr5bzfapUOq3/Rbk0HGPuzViJATA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T22:59:50Z"
  mac: ENC[AES256_GCM,data:drZ6LBHaUhNCl/ysAMtvn9JkcGQc2YBgUia06BU+05zLy02c+7YWrnuFsh+i/PsuoZJTjwmQ6i7x3jpq4CDkOQ61O2JvY8bIYc8VE3Us0zcmPUGyFCP8he6W5T0NtuPQOI69FuEnue2ulKiP00Wz8KbE0cni/T+wuzuUe7kkTEk=,iv:2UPLZ8Q7cj/mJkEIMFe5RU/8kaaHeq0zn8b6fb8GjuM=,tag:a298PXgNBszPa18lKxxUgA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
