---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-ingress-default
  namespace: default
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-traefik-to-apps-default
  namespace: default
spec:
  endpointSelector:
    matchExpressions:
      - key: app.kubernetes.io/name
        operator: In
        values:
          - changedetection
          - it-tools
          - stirling-pdf
          - web-check
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
      toPorts:
        - ports:
            #- port: "5000"
            #  protocol: TCP
            - port: "8080"
              protocol: TCP
            - port: "3000"
              protocol: TCP
#apiVersion: cilium.io/v2
#kind: CiliumNetworkPolicy
#metadata:
#  name: allow-changedetection
#  namespace: default
#spec:
#  endpointSelector:
#    matchLabels:
#      app.kubernetes.io/name: changedetection
#  egress:
#    - toEndpoints:
#        - matchLabels:
#            io.kubernetes.pod.namespace: kube-system
#            k8s-app: kube-dns
#      toPorts:
#        - ports:
#            - port: "53"
#              protocol: UDP
#            - port: "53"
#              protocol: TCP
#    - toEntities:
#        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-web-check-default
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: web-check
  egress:
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: UDP
            - port: "53"
              protocol: TCP
    - toEntities:
        - world
    - icmps:
        - fields:
            - type: 8
              family: IPv4
            - type: 128
              family: IPv6
      toEntities:
        - world
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-traefik-external-to-echo-server
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: echo-server
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-external-networking
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-traefik-external-to-blog
  namespace: default
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: blog
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-external-networking
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
