---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./database.yaml
  - ./media.yaml
  - ./matrix.yaml
  - ./sec-tools.yaml
  - ./cert-manager.yaml
  - ./external-secrets.yaml
  - ./kyverno.yaml
  - ./home.yaml
  - ./home-automation.yaml
  - ./labs.yaml
  - ./networking.yaml
  - ./observability.yaml
  - ./openebs.yaml
  - ./system-controllers.yaml
  - ./system.yaml
  - ./default.yaml
