---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: matrix
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-traefik-to-synapse
  namespace: matrix
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/name: traefik
            app.kubernetes.io/instance: traefik-external
      toPorts:
        - ports:
            - port: "8008"
              protocol: TCP
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-synapse
  namespace: matrix
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: matrix-synapse
  egress:
    - toEndpoints:
        - matchLabels:
            cnpg.io/cluster: postgres-1
      toPorts:
        - ports:
            - port: "5432"
              protocol: TCP
    - toFQDNs:
        - matchPattern: "*.matrix.org"
        - matchPattern: "*.discord.com"
        - matchPattern: "*.x.com"
        - matchPattern: "*.linkedin.com"
        - matchPattern: "*.meta.com"
        - matchPattern: "*.facebook.com"
        - matchPattern: "*.instagram.com"
        - matchPattern: "*.bsky.app"
    - toEntities:
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-bridges
  namespace: matrix
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/component: matrix-bridge
  egress:
    - toEndpoints:
        - matchLabels:
            app.kubernetes.io/name: matrix-synapse
      toPorts:
        - ports:
            - port: "8008"
              protocol: TCP
    - toFQDNs:
        - matchPattern: "*.matrix.org"
        - matchPattern: "*.discord.com"
        - matchPattern: "*.x.com"
        - matchPattern: "*.linkedin.com"
        - matchPattern: "*.meta.com"
        - matchPattern: "*.facebook.com"
        - matchPattern: "*.instagram.com"
        - matchPattern: "*.bsky.app"
    - toEntities:
        - kube-apiserver
