---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: default-deny-ingress-system-controllers
  namespace: system-controllers
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - cluster
        - health
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-snapshot-controller
  namespace: system-controllers
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: snapshot-controller
  egress:
    - toEntities:
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-kubelet-csr-approver
  namespace: system-controllers
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: kubelet-csr-approver
  egress:
    - toEntities:
        - kube-apiserver
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: allow-k8tz
  namespace: system-controllers
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/name: k8tz
  ingress:
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "8443"
              protocol: TCP
  egress:
    - toEntities:
        - kube-apiserver
