# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:kJRpGq9MR7teLybA6s8WdDTQBkmnjBhOIgJmlQ==,iv:uEtH1RXYCR/tOvvQ9DULl4jl+TUSPZ5YFpQuxKvcNAY=,tag:DdbwrFsIhPhPqTovYN2v6g==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSa0dTQVB2RnRSeDBSSEtD
        ZitCT0ZFQnRjcG9MQmdsV3grRVZXQmwvWXhVCnp4VVNaYllxOGpjNWJ4TUZuV2dH
        OFpkQ0Fsbml4TnNTZXdBVHhYRnBDdFUKLS0tIGptSFdRc0VmVHRteHNvb1ExbURa
        eStFczBOd0svbVRYdzZvSkpIRXFWdkUK4O9qzKdOx6A2sFchg9OPFdfCK0Syvrse
        9Nab6DwI8sBwNu/q89UekTcRfAQqjeqbEffG8p+LC2kdFtyDzPfr1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T19:27:37Z"
  mac: ENC[AES256_GCM,data:vjPS49tdTtB/Wlu8A6c31VkiqlZuKsLXu36xBbuIqvIZYC4x/aGjxjQFaCCPYNEjjB6cpbklJthu8Kd9Eah4Za8X0qhwTR+/wbufDETB5Rkwv1sslsKQO/tmRUPWnhp/Xn1TL1yoAeaci1Elx6oX/Dt4kqzVG4WbYtFTu9NOFss=,iv:UgnyjbQpyr6VIIqgl0wmP+DMVDOpId12pcr+c/H+jf8=,tag:s8Qh4vQuTzTKbFBU0xtJVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
