# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:XwrWmun+qvhp3t1wIJ/t2QRcLXsPorqk3SZYjA==,iv:EzTX+EW9X/kF/fQsT3t5abhhf21Mcr916Bv5Er9Tz2k=,tag:o5yYknHFGPJNFIEsyNKyYw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYkZoZTZiVklMT0FVOE1X
        VUNuOVpzSldKMlhKeHVNV0FmWk9pQ3BkYmlNCjh4ckJmV2tGZE9uTU1pZi9iT2tz
        dG1uVzhKaS9GdnNjd2s4eEVMQmZ5VG8KLS0tIGM2UzNZejgwdEpUbVY1Zm04bms1
        TkNZek54d0kvOWE0RStQcmxlYlJ1WjgKRsROkb7jO3QsxyrHReUlbTjKyAf5kfdM
        5V7uUdRzIHiBULy39RUpgw8tN28CLyxULKvSYoPDiuKUt9ooLVFdkw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T23:18:52Z"
  mac: ENC[AES256_GCM,data:tEgpEUqNxBak0wY4DzyYP0m9+nmaDkrNIsBs58UvPiU5MqD1xvYGspLeq6KtwK5pR04X5IEMjZBFJQPExdLPQzWNNUmyTJ1vz5YbpkmRWym406DabJVKMWj5QfP+OU9mYgOTDAZJedvMRcXntIfn1cV6nqiVVxTNzQcpcVfJQRo=,iv:j7mbE7ThvD4I+rQtn7P1cTaqDgh4t6XfPSBp6pK7FAo=,tag:NJ/dvYufv8EWR9ffvTCwzQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
