# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: dragonfly-secret
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:Bakcnr+ineiuU3XipFORXF2S2BBuqbCp7GEqsg==,iv:3DrraK7nIAffU375SylUk8YNJPzaip3HO4Fv8TbdKkM=,tag:CVYua51KhwUHdQqtTT5V2g==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArcmU1MWNON3FCOTlMZ0ZP
        LzVZanVFcnN3QWlhUExEanMycy9DQ3NYbVZ3CmtBT01SUWEySHBuYWZOeEFkSGI2
        ZjNpb1ZCeCt2WFRUNEhZdCsxOG8vcjgKLS0tIDBxR0t1Q3MyV255cXRuTlNRV1hU
        cmo4R3ZCaVdtY2NCM082K1ZzVXYvYzgKK8jefoBaTiPHKpb+PEeM+6qCFwdtmsAS
        6bYJmfOrh+ePNparUxMHWnhuPmWFEHlKRS0m7Uab2YZkTXa1IH+eRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T18:01:03Z"
  mac: ENC[AES256_GCM,data:jOrh9Wsg5TH5Z1PjqmIBulrfHZJByACEqKjNOtSpEkPDH8TQNq3Khefg4sakmIWl5yeaKHDkc5ugvcTspCvacTAED0YhyuFIFLrq8V8lUSquePdTAWQSGeGvHQET5iVZ2lD38uuoy0Pcg6B7Ew704SCteasLQ9GZX5GRPOSlZvU=,iv:CDvR8BLUkMTXM5Eb+grtNHm2QvUIxQ6zBKBH6ZcBHWY=,tag:EW3E4ZCKyxNcyzF4wKkwrQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
