---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-ddns
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-cloudflare
  target:
    name: cloudflare-ddns-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        CLOUDFLARE_API_TOKEN: "{{ .CLOUDFLARE_API_KEY }}"
  data:
    - secretKey: CLOUDFLARE_API_KEY
      remoteRef:
        key: "1cf0ff2b-9b45-482a-b0b3-b3c7000bdaf1"
