---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template.yaml
  - ./spegel.yaml
  - ./stakater.yaml
  - ./ess-matrix.yaml
