# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: rsshub-secret
stringData:
  REDIS_URL: ENC[AES256_GCM,data:iRWT74eMiy9vmwp0ez75MzqDNQiuXrzFyCkOv+ju9xlSQPqNGO2KmoukSxuiTpsKdLPV+lpXJ24cvE45aSt24cJ080gcqs2Sgf0Q+NT/a0Su,iv:Ki+d/4oRXkX6NFc7/GMHV+du11kL+WYwaEWFcVuWLU0=,tag:GPk3ifnbHPz+nCcikj0cJg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBONHlTNWtCNXZiNEhWdFV4
        SHZpWUs5U3ZYQksyaE1OT3NKWDhYSmw4TnlZCmV3NjI3Z09TZUdWUmxGZEpROVBP
        VUxucWVDdTN1Z3Azd3c0ZVlGblVUaUUKLS0tIHVlcUJOZjN6ZGNKMDFFY2p0RDdE
        Z1kvaDljc05IajJiWndIZXllQUVyMHMKdU08YkysINXbs4OzxPmez3eBwc4UnXVP
        OyK5bmdZ98md9nGTo5OsQ+7LMJAp9iBbFocr/TxB6H2tKg3N3WgkNQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-25T18:01:03Z"
  mac: ENC[AES256_GCM,data:f0gq6g/vUBrbkWtJnVgTI7EGMSOapkq+VfJ1vwENGtFLRZPxI8k6JF7SMoUYsg+V1NfgBQOa1iAZVVCqpgL2c2rWAtj9zpZcmuvmv59wp1XTPOjxuIVqYQEZFe3mxpH9TtBVVbZZIuMGOZoLE768U0XOQiDiD2loJx5upiu0fg0=,iv:CgAvpV9Gc53DpL/7rARhJWLVUko68Yv1F7YJyjSnzBc=,tag:RZIjA+xLsjtEMCWZFM74mg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
