---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./echo-server/ks.yaml
  - ./it-tools/ks.yaml
  - ./web-check/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./sec-tools/ks.yaml
  - ./blog/ks.yaml
