---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./it-tools/ks.yaml
  - ./web-check/ks.yaml
  - ./stirling-pdf/ks.yaml
  #- ./changedetection/ks.yaml
  #- ./playwright/ks.yaml
  #- ./rsshub/ks.yaml
