apiVersion: v1
kind: Secret
metadata:
  name: smtp-relay-secret
stringData:
  SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:4N9lXi6sUf6vtx7NPV0P,iv:B5xvk6K+w8YlbAxLLVu1mu79XUGgZIea0WDRQtpH484=,tag:SeFcioFVG5nx/BL8mSJssA==,type:str]
  SMTP_RELAY_SERVER: ENC[AES256_GCM,data:xV5Ccex0qZJdhEruYslx,iv:bCIyjbq34vSpAuglkBQo5m2JRQFEkhyIT3R7gzcPqqQ=,tag:34PB7iXx/m7yRvrYv2JOfw==,type:str]
  SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:h1EIRt58kZ0=,iv:erlQJwg3bcBckvUpwWqJT/n9IYTUhFQBt5/QdSDNdKw=,tag:xw78krW8XaYRhfsikUmhvw==,type:str]
  SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:hIgVh3Mi1l9gwC2QE+f0Lz+AvihJFp+djDnjqJSx1xtcbH3sSNE=,iv:aeu/COwKamGsy1AThS0WfGlHeajN5hG6gzEhOOFjDxM=,tag:oU+KBECroQqSaKbf8C2/bg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrYjJQdndrd0ZjY1kxanJP
        Smtrbmd2eEs3OTFvc0R3QWd0MUVpVUNMekMwCnZsTWJKWjJRSEU3WTdycGVROHVL
        ZFd4dEpQSHM1L29PT1RQSm9XOE56NnMKLS0tIFd3VEZtQ1JyWHB4Z0VzbThtcW54
        VUFvY2Z5TURhR3hvWFVKMFJqdmFaOHcKY02QuHwrnjg9emMq/8bbML8r7+CauJAO
        vgLeawO/T9KgZP8IltDrzcQiduVDis1+YvaEbjO0v55RHNWodzgGuw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-24T18:13:25Z"
  mac: ENC[AES256_GCM,data:1z11HU8v0oofo8uZqTtzCzTjwti/e1de3Q2UTGm40OelXlZkgntfmHKM4IBo/QePMpSYzdoyQkKsQtHeXLWmau8o9vhUiKzFqTUFCzbYfIac9xCyRb+jlRB3FfBBZVl8XjxGsYQDQw981rZcNVcNZ5dnHGWyffQoWZ2srDcoQ+c=,iv:XreNAYBvH/PV1IbHi+iK84OAxFipFXDSubmbfmJH6qo=,tag:q+zcHE2kXB92vW6J99E97g==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
