---
id: twitterbridge
url: http://mautrix-twitter.matrix.svc.cluster.local:8000
as_token: "{{ .TWITTER_AS_TOKEN }}"
hs_token: "{{ .TWITTER_HS_TOKEN }}"
sender_localpart: "{{ .TWITTER_SENDER_LOCAL_PART }}"
rate_limited: false
namespaces:
  users:
    - regex: ^@twitterbridge:${SECRET_DOMAIN//./\\.}$
      exclusive: true
    - regex: ^@twitterbridge_.*:${SECRET_DOMAIN//./\\.}$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
