## yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: grafana-secret
stringData:
  GF_DATABASE_USER: ENC[AES256_GCM,data:5Jb+hrR6NQ==,iv:WrETOs2fTz/mLTVHE3NyE1cce7jIJvTwbKA2VJn6Ayw=,tag:EY7nABoOpXvAxma6L46rBw==,type:str]
  GF_DATABASE_PASSWORD: ENC[AES256_GCM,data:48KD1w8wVOR/7CHBtcAM7eMcp3yvZEB886o/Ec8mpxBYsqnhA/mdDPkn54o=,iv:BeJCGsACGu1rGLiviHoKV2+dC1evmc6yO//+0fDa2AA=,tag:9KGy3k7+J9pU/M5HYmDfXQ==,type:str]
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:UeAZrlPfi3JPJw5lyegla0UlYlZIPLCka52WvIPY0+oR0o97KUO37gjLh8d7kWOz,iv:VxfWAzISv28sTCOzRpZLHjQJSrkqH9uBuKgH5WsLS24=,tag:/QYQkSb1r1YFyBwtOlN3pw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5cFI1WnhMNFhUTldBNjB3
        SlpLSVp0SUlSKy9KcVQrOG5xb3I0SkpjbVNJCjl4QW5sYTQvYUVBM1J1eWhselR2
        NWlweVJ4WXZ5aVRaUHR0SU9UeW0xNWsKLS0tIHdVTlc5VEttR3M5UlVOTld4SVlO
        VEtPdlFaazZqVm5veDNuL05aWlhGTEEK9UxfX6toy5WI3MFfXby7HqyQ+HYD4MQa
        Ya0VdrO+JyRqpnAh6C30yr3eVmrMZNzZ7VHShrYdDmMoWFz6UBsW1A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T19:16:18Z"
  mac: ENC[AES256_GCM,data:7NWQf17OxeS8JFgH5ASNeSVdqInFlk+bEZJ0sbGBBMzkHApLpYZMr7teifM3FkNEbT/F+Z0Y8hbXJABXj0Ev89oHqNor8jYgABJt0mFc+a/t2at9ixB+2fN1jKWBGR+KCznyZQFlrmSrjtgA/gteLbsamLe9+OVr59M382gp1S0=,iv:YeB6Kp6xW9Hv/spzr27LHV2Ezi2W6JjkwrzX9XiRN/Y=,tag:SMYO4kxxQliJDQ18ziL16A==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
