---
- Overview:
    - OPNsense:
        href: https://edge.${SECRET_DOMAIN}
        siteMonitor: https://edge.${SECRET_DOMAIN}
        icon: opnsense
        description: Edge networking
    - Unifi:
        href: https://oob.${SECRET_DOMAIN}:8443
        siteMonitor: https://oob.${SECRET_DOMAIN}:8443
        icon: unifi
        description: Unifi Controller
- Devices:
    - n1:
        href: http://ms-01.${SECRET_DOMAIN}:8006
        siteMonitor: http://ms-01.${SECRET_DOMAIN}:8006
        icon: proxmox
        description: ms-01
    - SLZB06:
        href: http://slzb.${SECRET_DOMAIN}
        siteMonitor: http://slzb.${SECRET_DOMAIN}
        icon: zigbee2mqtt
        description: Zigbee adapter
