---
- Overview:
    - OPNsense:
        href: https://edge.${SECRET_EXTERNAL_DOMAIN}
        siteMonitor: https://edge.${SECRET_EXTERNAL_DOMAIN}
        icon: opnsense
        description: Edge networking
    - SLZB06:
        href: http://slzb.lianas.org/
        siteMonitor: http://slzb.lianas.org/
        icon: zigbee2mqtt
        description: Zigbee adapter
#        widget:
#          type: opnsense
#          url: https://opnsense.${SECRET_OLD_DOMAIN}
#          username: "{{HOMEPAGE_VAR_OPNSENSE_API_KEY}}"
#          password: "{{HOMEPAGE_VAR_OPNSENSE_API_SECRET}}"
