---
title: Dashboard
theme: dark
color: slate
headerStyle: clean
#favicon: /images/vines.png
background:
  #image: /images/greenbg.png
  blur: lg
  opacity: 11
providers:
  openweathermap: "{{OPENWEATHERMAP_API_KEY}}"
layout:
  Overview:
    tab: Main
    style: row
    columns: 5
  Services:
    tab: Main
    columns: 5
  Home:
    tab: Main
    columns: 5
  Media:
    tab: Main
    columns: 5
  Tools:
    tab: Main
    columns: 5
  Observability:
    tab: Main
    columns: 5
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: false
  showSearchSuggestions: true
  hideVisitURL: false
