---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: cloudflared-secret
    template:
      data:
        TUNNEL_TOKEN: |-
          {{ toJson (dict "a" .CLOUDFLARE_ACCOUNT_ID "t" .CLOUDFLARE_TUNNEL_ID "s" .CLOUDFLARE_TUNNEL_SECRET) | b64enc }}
  data:
    - secretKey: CLOUDFLARE_ACCOUNT_ID
      remoteRef:
        key: "56bbf43e-b051-42d4-b581-b3c700097f11"
    - secretKey: CLOUDFLARE_TUNNEL_ID
      remoteRef:
        key: "7aa26d0f-1cf0-4a6e-bc84-b3c7000a78ce"
    - secretKey: CLOUDFLARE_TUNNEL_SECRET
      remoteRef:
        key: "e27b1b38-053b-4dd2-9972-b3c7000a87d6"
