# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: recyclarr-secret
stringData:
  RADARR_API_KEY: ENC[AES256_GCM,data:ki9ZqlbLQbP6aqjKLJewJh4TDCtt8t6TH+2H/HKZBE0=,iv:Z+BFJsOenQpgtspjg4Vbs9VVuP/qHo4v9RzlEiHmI4M=,tag:BlCG5b42v4gSAh+/IvFS+A==,type:str]
  SONARR_API_KEY: ENC[AES256_GCM,data:z4EAVWhb35VJoNgYendWWYwmucHvY/Ztqaz1/UuUOtWTQ7lUEFJuOmeo1wM=,iv:sIiJvcxrEEIx238RjiZAaKwki6UUd1TRPLkfq/2Jchg=,tag:MVIxsPWj633oq0ZOhC7lkA==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBcnNqSndIUjV0SEtqajJC
        OGJ6c1JsOWpnbEhRcXZxb2xlTkRxMzZlb0RzCllTZmNpdnk0YjZxK1B2dXZjTWFq
        ZW5paExtUzBZVW5PUnlCR0tqaVdJNlUKLS0tIFMyKzVOekxXYytMQkJuZlBYeTFm
        cGZNZWNVRERPZm1ENkZDdHVMS0dXeG8KIgh7oFlB2Ewykylw3Qb2rqR3us43ZW5O
        F+/bQFooYLs4tmSuJuCXLta5uH/iGM/rwhmbnrR/CIzij0kXFtbAZQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T03:11:34Z"
  mac: ENC[AES256_GCM,data:uYZiGFTnei2rwJ5XM5HkKgNVAaN6EfhoZvTjOZX553A2ah4tgp2BsC6RJhmTNjAxtidZNQqpKt5oSO+tWuazKg2+PE67sq9Ey3gcEae3llqM2/ikQhO1Us/2Ya9oguxM+APXkwMzh1AF5HpXNAIMFryHFtFjDsr0KmjJd9uAdK0=,iv:0PwUVMSX8kzl4nmTrvSG3ZHg6yf1mBDAlrXw4wVvWpU=,tag:RbqvO82rg2E6vSscqa6Y7Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
