---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./homepage/ks.yaml
  - ./linkding/ks.yaml
  - ./miniflux/ks.yaml
  - ./syncthing/ks.yaml
  - ./zigbee2mqtt/ks.yaml
  - ./home-assistant/ks.yaml
  #- ./immich/ks.yaml
  #- ./owncast/ks.yaml
  #- ./grocy/ks.yaml
