# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:Nl/2z3ZvSgNkRyIh+aqwfHmTZmqDVUcLOyIwZyLD5fAl6WJfl2vf9vR7v9A=,iv:1NXlBPVYUvxcpgCovy2sPpJDqoRjEcEKZBN8/q+gRBI=,tag:/gb1NWph4zrlahgyylH+WA==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:eIeKYWmasN6zKKLDwWid5kgW2egaDPjCr0J6NNF4CrLXuoW210AqNDi+9cCw00zn,iv:dXaw2gV0XBrXIv3pXZ8rCn2B4NRhGwx3OoaXtcPg8L0=,tag:fgv6jhETKZgOuiJUYY5ing==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:bQjXNMJZ,iv:FN1SvaxknUqfrEQF8/jkA5XQq8V+EgWOCtCoNEiXAKw=,tag:SK87Rs5Oto4hB4rhUxTPMA==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:MhFjcER02qyB4FDHR625xN3zW957biy1ctPUGRZysruajtwQfp1/,iv:4Zb7DkM3YxKxArMfdj5iYP4UyX8fDxPQrma/Q5ZwmIQ=,tag:KUpdBwL40bXibry8eAEYfg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDbDF5aExtLy9hNHJ1aWhK
        UktRYmxkQXBnb2ZLM29kdmpucjNxdFJUMUZ3CjRoc005cDBlQzg1MFN2TVFxWS9R
        S200ZnVJZXovQWFaVzVkMFl3dmhiWEUKLS0tIGZma2t4QTNlU3hOeU9makVJUEpW
        aFVqOE04TUtOaTVtQ01BYXR6THpCQUUKkBewUw8PCLrNReRp3IPW2olvXXJ3lkGm
        66hnwA7wrCSAHGUOWUZO82neCN6GklC/8TpyLoTDlc36IYv3ck4w6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-09T19:37:40Z"
  mac: ENC[AES256_GCM,data:8cn3wubGZPeVq9/WxnVSq+TFuWRJpzEvRu1pULeKKHPi2hVF26Kip/i6mYi4iGHrmYIdIvGV5HBnx0mAAdPo4GTup0KfQyMb/Gne/QgQHfvE5yc8M0EX85e5Szt3h3RjaC24rKM8JGI3rcI1R2LL5xqYGyW0ZNrsrsolOtXcuPI=,iv:LOXARxbPMoUQ06rHwSRVB05MThR20eywOYLf9rumzlQ=,tag:2oJVoYqZZIZeffBjGCrapg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
