# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-secret
stringData:
  REDIS_PASSWORD: ENC[AES256_GCM,data:VNr599asUBIuVMIXjZFG/DzRaukKjXmxzmhBGQ==,iv:X7owNPFp9EZNXwuPtaMn4W1Cm0cPwhOHMjlDxPv7RWY=,tag:Du88sOsYKfTVu+0yhkULrg==,type:str]
  JWT_SECRET: ENC[AES256_GCM,data:SxKFB2HZqKCFW01obWIqNCXYUNJ5+wTWx/OncDBiod3M/fXqc7PNfQVTShCvU3fK,iv:kXPNbWXv5B+FfBApLu2Hd1O+qhDURuZDL6O/42VVmrs=,tag:DGH0bKTx3GmnDNqRDX/rbw==,type:str]
  DB_USERNAME: ENC[AES256_GCM,data:GXB1skNV,iv:hzQxKSnRQNx28AjfOQp96JyagsNP0H389SwtnC0L7Vw=,tag:4PrLZTOgzMH1oRNXhKPG8A==,type:str]
  DB_PASSWORD: ENC[AES256_GCM,data:DZynl6mMr1yEdn0BRjxglTtwcyDBOoHtPG7S/baFz34H/oDXpnI2,iv:aPnZY33XWa46qfHxnUdpYX1v+Jzb7UQGioqTdHVnd0M=,tag:+LbFW0LmOktpXsWEbE/5UA==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4T1RxeGIrZldQMlFkdmRo
        SjRocUFtSjJrOGNZVTY4cHRqTlVqa2tSWmtBCjUzMytRT0E5TitnLzY0K3p2d2l6
        d2ZXS3pmcFphd2pTTUwycEkyWFdCeGMKLS0tIFczL3lnbS9MeUM4Tk5wNkFoK0RT
        SDZXdjZVcEkvMHJMQkdFZEQwb2RTUGsKVQJncnw1X+IWwKQeK6Fzgp1/KWho1LYV
        tymRxcPuldJH1sexA7wX8PLs5kY1ioK1rvoAzk783TUmQlX4dxhCIA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-02T16:25:49Z"
  mac: ENC[AES256_GCM,data:79DHPHebytK90kNDRlL88rSw/Hyz+FDSE3ucZ+Kz9FFZi84VzA2itURxa8ub8icRFB7gqZaQA0srbOJ8v5gzgrGz4ncIV+JOOgLNmLBQ+I/5B+BrIVGAkvAZR1e0c9AYKSBxd4BrLeoYl7Hq8Phiq+pCUFVU8rGUI2iBIKfI6rY=,iv:Zn5UQT9bXEJuOqEXA4mAzta/TEBBlpgBAbO7sorUhas=,tag:WpPhWMqmQBcMj9xkm90N6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
