# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: immich-secret
stringData:
  #ENC[AES256_GCM,data:8orxbXkzDGKB2FYDt1zpL5ERsVffESvknHsax9HTxTi0n/fZaJykcikDcB4=,iv:1+oqWN8/fJzqc1rHvIy9wj5P3oeX0GOkgZqaEv8nC5U=,tag:42pRCncTyiAz8DZ7t7licQ==,type:comment]
  JWT_SECRET: ENC[AES256_GCM,data:EMmGlgIPJX8VdWclTZHuFE1gBDDR0trknyxWvf4swdCIaSWs24dYZ6Ic17feQp1E,iv:t9xtDVN0RvCcR7AITM79mX9K2ExuO3PT7BSH4+v5yUs=,tag:XX1RE0eJ7g3e0H2MeCOxvg==,type:str]
  IMMICH_DB_USER: ENC[AES256_GCM,data:/AJSL0Yd,iv:JV/WS55aGYwr+4msU5hSS86EtlNgYMglVyCW+atera8=,tag:wPydT8ZeE1Z3tbyDjo62ZQ==,type:str]
  IMMICH_DB_PASSWORD: ENC[AES256_GCM,data:82B6BpZnZHg90YyO2kGDS+wSNn07DUdbR3ieDrZZY299flT3YRfJ,iv:RnAfj9CZ8O9BP1WeaB3LCLjAn2RzPAaysl4pqPWjGO0=,tag:7G0oYClyMHYxS8sBkqTkHQ==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZm01cnBxUTBQNERxM3FI
        cjdUMERxTUdCTFA1bTB5QXVOcUdmZE8yaG1vCm1kSk1KUjRqSVpQZCs4S3JhTTVO
        b3ZQaVQ2dmc2MzRVK3NkMzJ3Z0kweE0KLS0tIGZUV3I4SzVMbW1hYVlvSm1CSGxM
        Rm9WQVlsaHRPNFBxUXRLN0tBQTRZVVEK4vGF714DAOdma5kndjbPLNct2Ro9deoK
        WboiLjRTyL5cQLx2TSrYsqyXTwW+6ykgmvSjyIt6joswBfO9mi1VQw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-01T18:43:27Z"
  mac: ENC[AES256_GCM,data:jwvKAEohOPA8EKWlqIqQUmnAXYWDxiXn7eim9PiLxKtiREiRFxD74kNShoFp5cUYt+FK/vxGznXA829FDdHWy0wLf82Ww+wUAcFGaX0IrNR6okmdvRDcatdQfjbBgSv0TU48xTHqhBK3MZjyrIiJRQswGgI8Fd/5HclsUfHduwY=,iv:va+1DQRG8VQX1v1607k7FHkaHRYDBEpjbhoOXde55GM=,tag:CNrLI6SGtU5ALWrPwS1ndw==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
