---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kyverno.io/clusterpolicy_v1.json
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-rootless
  annotations:
    policies.kyverno.io/title: Enforce rootless behaviour
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: high
    policies.kyverno.io/description: >-
      All indicated containers must run as non-root user. These containers do not need
      root privileges and running as root increases attack surface.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: enforce-rootless
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - matrix
      validate:
        message: "Indicated containers must run as non-root user"
        pattern:
          spec:
            securityContext:
              runAsNonRoot: true
            containers:
              - securityContext:
                  runAsNonRoot: true
                  allowPrivilegeEscalation: false
