---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  #- add-seccomp-profiles.yaml
  #- audit-probes.yaml
  #- audit-requests-limits.yaml
  #- enforce-drop-all-capabilities.yaml
  #- enforce-network-policies.yaml # TODO: Fix this
  #- enforce-no-host-namespaces.yaml
  #- enforce-no-privileged-containers.yaml
  #- enforce-read-only-root-fs.yaml
  #- enforce-rootless.yaml
  #- restrict-image-registries.yaml
  #- restrict-volume-types.yaml
