# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:kIU8L6zQ5sw=,iv:SShFfBTFOheeUVjLx1d7u2lMBayrvj7Df33lThaJxqI=,tag:sV4EoeigzvrgjPaKL23DhQ==,type:str]
  password: ENC[AES256_GCM,data:rWc505icBJjE0hXtXrNoZvJKOHqU1sYbljeosA==,iv:NNUMgVXNuvSlWW85RvIG+bMOZeZnS8ybqfBw8EWg1vg=,tag:dLTDtXe9xR2DOA6keA2WGg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1SHdTaXc1cHdQdDZTeHEz
        K1QvSDJLS2RXTERBc3ZyR0JsSHJCL3JwQ3c0Ck8xMVNNQjlGUkdIaU9CQ2I1WUc2
        Vy9lYWpGOVJ4TWlwdnBEN3JPTEl5Q3cKLS0tIFhkbzg0a2RxTFltRmQxVlNFRncz
        YzBNSzRycndHMFRsNVAvOXBZVldxR1kKlyhxUZ3cxwACF5N500H7s0fucS3X3leB
        iDmLY5b1STQ1gs8jaBwqULs6gZyc/SNl9ETOaXgMv7Y7lMm7asD3+Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-13T00:12:01Z"
  mac: ENC[AES256_GCM,data:c8K0FTpk7O1ezwaDGXYTQaySb6NpNDKk7hMuda3uB7WaytMhAAckAgvs9ZNIcKYA6+aCWalWqWaDaKjx4QNpLErc3RmTAuSiuc47akNzb9mDHabzhRex9PoaiTHJ1yhMrARqocD9ooQTnnqQvknyMSWypm6P4iOd3WMN3ycorDU=,iv:gHyzkWM5KsSCxj1/rLme+yR9/P8E5Xj+l+zaMGG7Vmo=,tag:I30XCyMuh1tR/VXZ8d7utQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
