# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: cloudnative-pg-secret
stringData:
  username: ENC[AES256_GCM,data:7xSQu7KAm+M=,iv:wHnLl/pGzv7MgZL2ewIK+x/bPdsqoE1YKoIAsRFxw78=,tag:qyaoNhj273ho2BYosBSTfQ==,type:str]
  password: ENC[AES256_GCM,data:/JyemWEojF4udZRHh65Sk11L14B/He4r1LoaZw==,iv:DS/4GzNsQ9C8plx6F4GTNZ/+FTO+Y3TkiS9/YV7xmtY=,tag:e2pfhl0oQOK6awVAGZuvYw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkZTlXY1dSM0FhU01PNHl3
        N3NnOW54aEpMcnIvZHhPMWxuQ091QUQyZ0FFCkducTZDZGxicUlQY3JUYzRjWkVt
        aGJRc2s4b2NzK1diZ0tOQTVMT0l3dTAKLS0tIC9hcWp1YyszbkRXaWY4R0hTWm9N
        czAvSUZSMDRuUVVNU1JBNVVZakpML1EKt/zRtc5VZ+te8lfcgWQ/TYjXre6uv7Y7
        2+eTpdSW5tMudvvXU/6UNT3A5A0XgbH01cDne5+qsleH/0Li8ws8+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T19:12:43Z"
  mac: ENC[AES256_GCM,data:F7awhblZT9lwPbaboAsQdRVfONqFzTVZGLYO0RlqKX5oJ/Y6460rr/3oR6yRxkr2UyGTa8azro1eodhGK2HKigcOAvwJ72qRS3Bvp6G4dimKag5nZ5wjPliUsgMmv0XCD3dFNz9yXYNFj6pMjKKi4KQQ4Lksq2WgIIOeIbR4A/w=,iv:C9GC2NReI6TdSqsmlcnNOPUmanhb7VBjltGic16egwU=,tag:xhNEeXAZq3rUopTb/CfG/w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
