---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app synapse
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: matrix-synapse
    namespace: flux-system
  #  chartRef:
  #    chart: matrix-stack
  #    kind: OCIRepository
  #    name: ess-matrix
  #    namespace: flux-system
  values:
    serverName: "${SECRET_EXTERNAL_DOMAIN}"
    publicServerName: "matrix.${SECRET_EXTERNAL_DOMAIN}"

    wellknown:
      enabled: true
      image:
        repository: ghcr.io/rtsp/docker-lighttpd
        tag: 1.4.76@sha256:b4b58d217a35dbd6cade82927677de404a46fb3d2b1d5fcb42042b6a6f17b2fb
      #      podSecurityContext:
      #        fsGroup: 101
      #        runAsGroup: 101
      #        runAsUser: 100
      #      securityContext:
      #        capabilities:
      #          drop:
      #            - ALL
      #        allowPrivilegeEscalation: false
      #        readOnlyRootFilesystem: true
      #        runAsNonRoot: true
      #        runAsUser: 100
      client:
        m.homeserver:
          base_url: "https://matrix.${SECRET_EXTERNAL_DOMAIN}"
    config:
      reportStats: true
    extraConfig:
      email:
        smtp_host: smtp-relay.networking.svc.cluster.local
        smtp_port: 25
        notif_from: "Matrix <matrix@${SECRET_EXTERNAL_DOMAIN}>"
      presence:
        enabled: true
      enable_3pid_lookup: false
      app_service_config_files:
        - "/mautrix-discord/registration.yaml"
        - "/mautrix-discord/double-puppet-registration.yaml"
        - "/mautrix-meta/registration.yaml"
        - "/mautrix-linkedin/registration.yaml"
        - "/mautrix-twitter/registration.yaml"
        #- "/mautrix-signal/registration.yaml"
      use_appservice_legacy_authorization: true
      #      url_preview_ip_range_blacklist:
      #        - "127.0.0.0/8"
      #        - "192.168.0.0/16"
      #        - "172.16.0.0/12"
      #        - "10.0.0.0/8"
      url_preview_enabled: false
    #      experimental_features:
    #        msc3575_enabled: true
    ingress:
      enabled: true
      className: traefik
      traefikPaths: true
      #includeServerName: false
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-production"
        traefik.ingress.kubernetes.io/router.entrypoints: "websecure"
        traefik.ingress.kubernetes.io/router.middlewares: "networking-traefik-middleware-chain-synapse@kubernetescrd"
      tls:
        - secretName: matrix-synapse-tls
          hosts:
            - ${SECRET_EXTERNAL_DOMAIN}
            - matrix.${SECRET_EXTERNAL_DOMAIN}
    postgresql:
      enabled: false
    redis:
      enabled: false
    externalPostgresql:
      host: "postgres-1-rw.database.svc.cluster.local"
      port: 5432
      username: "synapse"
      existingSecret: "synapse-secret"
      existingSecretPasswordKey: POSTGRES_PASSWORD
      database: "synapse_db"
    externalRedis:
      host: dragonfly.database.svc.cluster.local
      port: 6379
      dbid: 1
      existingSecret: "synapse-secret"
      existingSecretPasswordKey: REDIS_PASSWORD
    synapse:
      strategy:
        type: Recreate
      resources:
        requests:
          cpu: 10m
          memory: 256Mi
        limits:
          memory: 1536Mi
      podSecurityContext:
        fsGroup: 666
        runAsGroup: 666
        runAsUser: 666
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 100
        capabilities: { drop: ["ALL"] }
      annotations:
        reloader.stakater.com/auto: "true"
        prometheus.io/scrape: "true"
        prometheus.io/path: "/_synapse/metrics"
        prometheus.io/port: "9090"
      extraVolumes:
        - name: mautrix-discord-registration
          secret:
            secretName: mautrix-discord-secret
        - name: mautrix-meta-registration
          secret:
            secretName: mautrix-meta-secret
        - name: mautrix-linkedin-registration
          secret:
            secretName: mautrix-linkedin-secret
        - name: mautrix-twitter-registration
          secret:
            secretName: mautrix-twitter-secret
        #- name: mautrix-signal-registration
        #  secret:
        #    secretName: mautrix-signal-secret
      extraVolumeMounts:
        - name: mautrix-discord-registration
          mountPath: /mautrix-discord
          readOnly: true
        - name: mautrix-meta-registration
          mountPath: /mautrix-meta
          readOnly: true
        - name: mautrix-linkedin-registration
          mountPath: /mautrix-linkedin
          readOnly: true
        - name: mautrix-twitter-registration
          mountPath: /mautrix-twitter
          readOnly: true
        #- name: mautrix-signal-registration
        #  mountPath: /mautrix-signal
        #  readOnly: true
    signingkey:
      job:
        enabled: false
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
          runAsNonRoot: true
          runAsUser: 666
      existingSecret: synapse-signingkey
      existingSecretKey: signing.key
    #    workers:
    #      default:
    #        podSecurityContext:
    #          fsGroup: 666
    #          runAsGroup: 666
    #          runAsUser: 666
    #        securityContext:
    #          allowPrivilegeEscalation: false
    #          readOnlyRootFilesystem: true
    #          capabilities: { drop: ["ALL"] }
    #          runAsNonRoot: true
    #          runAsUser: 666
    persistence:
      enabled: true
      existingClaim: synapse-data
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              name: synapse-matrix-synapse
            patch: |
              apiVersion: apps/v1
              kind: Deployment
              metadata:
                name: synapse-matrix-synapse
              spec:
                template:
                  spec:
                    initContainers:
                      - name: 01-init-db
                        image: ghcr.io/liana64/postgres-init:16
                        envFrom:
                          - secretRef:
                              name: synapse-secret
