# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: synapse-secret
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:4XU2wHg9c4iBzSZbVy15EdqOCKnD2zEAvYpK3Sj1LjQ=,iv:DnAcIhpcGjh6DLsfksVh5YnaOZaNEN9wbG38IGP/zuo=,tag:F9V2WBD9dW8xCCNnJU2MNw==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:xg+rKCkermTavoMCrpiBSh+SvttwtoExxrDfUg==,iv:97b+RB9ezNIwwmUc1rm0fNThnNhMAZIdj9ur8wlK40k=,tag:WNoBR9Vdu1ZLSU3cDZb9QQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:zvzMW55+9Q==,iv:PkTzCRNXYhhMMhTxaZgRquShCXEfLZPQY7Vudx68v/s=,tag:4AsY4RjTU7KG+5f5mFP+8w==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:dubcLlrWjVF7Fbb1fI57mJFvwrcEKA1gRzl7UHPA70PLZGPPG27UOA==,iv:HrChhGx4vFCJPsdVC6R2i4EOyqrrFu/kWFXz8SDFytA=,tag:vKdrAPPP7pdltl2IT80qMg==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:8wyECiSpLsRgjITZECd3SEpH0Bc5Ou8gpWOwbA==,iv:Kp0IH5mYinL2ruNWisxzRhLczc+gV8JcBGZb09MFwOM=,tag:5B1Hxu+BHqVAWQk0FK5JgQ==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Vi9nE1X3REghBAJnjKjERDiUbUWLAfU4TsZDwB5Rmo0=,iv:4N2tl+qGOt1qsrQiB1ItRIrTGAD/4ANafVMP7MDGSWc=,tag:y5SZSR4N917bLwvjUS8NjQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:8g806jYQSvDidA==,iv:vkLdXHx0L+GS4lAdIx08/5hP47cVXNjbkP70l5cSEMw=,tag:s+pyqT/4dtGX7q5wAeJWsg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnWlFBdWVMR3NZSjdnRTFK
        UEdYQXF0dkFWbWN2d2ExMmZ3R1EwSDRVZ0hnCnJQZ2NBT2krYm1LNUowTmJtalRm
        R3pqUHVLM1kwRFlSdUdyYytoVkVnOVkKLS0tIDUrb1RFWWJrSzM0ZGRVd3N0NnVR
        NUJSeDBqSkluMDMvSzJ5UHl4ZCtEOTgK1ZE0x1rCs4iTsEy+ZhJXMn8Yejv9d96O
        7Q/HizMNLdw8Xty0PHISKTkwDxGLfnWvXoOA86HvNAVWEW9pycXIXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T22:14:49Z"
  mac: ENC[AES256_GCM,data:qp3x8aoPI9MyqDIOoWn5fyFh9NPh6WiTvVI+SMsC4StXOqf0DrlNFf4JGsxIucxoh9ieEknxYUdnpR3rjtSaHYPUpQ+2KhT8rKFAOTXlAg2OVcTbkL7wv3SOdq8H1hdlp2ferLelmcaJQV7rimJRSpxa/xAiAAU6+gHvm3Ad/fc=,iv:o1q9wqh1l3bdhESLieiCmXGoHkkUYrNhOgOu1q4P8iQ=,tag:1QxF9cvI+Pro/vBqz69zGA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
