# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: synapse-secret
stringData:
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:erkMKcZa37QlUBRawt4INvjMu6dax5PjdMu+/7xLXf8=,iv:j1TZqqhiZkEXJ57S71z4TL+fp3K3kOR+y0yr/3j9HCw=,tag:MQKVGoaKBGM3WT9T+0Xx9Q==,type:str]
  REDIS_PASSWORD: ENC[AES256_GCM,data:/hK6ZZ+X3UwBCNnf7yGtd+ZS5uVmjmkSCDyTsQ==,iv:zzWtdQVuMb86hFbLbFWQwb+0lP/rhe6+F0prlqHqXMY=,tag:RyBwRnS6cE5mxrulZ8f7wg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:/+4+YBbHDA==,iv:AhFUgPohXW6kGCp7z5lvY/EvhBeP5Xr5UWLfXWksKvA=,tag:IB7nBnqPFr11o5Npqwru8g==,type:str]
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:406fYvM38NC5H2DduQeWZ42nRGycnrqg5QnCdnpt/WFgoLZpQYlI3A==,iv:ZAe8T9JeaaThi5+o9eK6YuXNNDNP8ZYuxMZ118hk4AA=,tag:C2/Sq+P2n5ZJvN1nQvpuxQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xs6hcyl+WwhSOZf5rEhr28eVY68nYBOkeJQ6Mw==,iv:haGo3BzryNNz/ah3vQkRDQskhKJ0G/wSBDtuhyzrhqw=,tag:wz6qIZHj1ICXtt8pSBJP5A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OB/V6UwKRuvS1Ikw+0uHq8wUlFp9MCA3QFm2OpFzSQU=,iv:kseCHTrraQCsmXDrj+3Zov4GCMuFBJaG3h1mxsMXmEQ=,tag:TA9RoIFGV7uGPP6mIt4gYQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:n7oMu3mvecnTWg==,iv:9EXPXBfVPYwDV/aHtffpRCF7VYwl3ceURqN+3bbkN3w=,tag:lJu2GSNOLfdrB9XR2aE7hA==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6VVZoT1R2eE93TkpCT3BH
        ZmJzRnB0M3ZKVnpOMWFSeXJZc2xjSzZpOUcwCkZheVRnNllsQzFJVU5VSER5UVpV
        dUVmUjE5bGliNEwzN0lrbWlRbjI1aU0KLS0tIFdMN3BmTVFtc3IvcFd5Q1JPNXVD
        WlpNeS8rYWRGSU9vNEl3M2FSNURoRXcKvks4dtT4qOa+bfacDbAfOyzawwucnUx/
        h17o5y4ek9RPxAQM8ELPeJ0MGX0cu4QpoaYRD+Tfhco1kfuCYyenrQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-25T19:14:24Z"
  mac: ENC[AES256_GCM,data:ZcmQERyh2SAG9VX5oF7b1bvW3guzBBBFW7Ifzh8F7t73XJZhkSDtRuu3OW5l6K0PrNwVe+mlz9f6XMHsZ3B+R57mJ3yVXEvlTASUmR+j3ReI1sAAcbCC9Q+M+kRBLl+zySZXl+RXOO9ccjlQK9brK6ICTkbrBrlMIG6vkj6YWGg=,iv:WyctuGI7DvWPTmEYsvuDF/tlkAxeLG7PqxyKXIU8LpQ=,tag:5K7Z/tC+dZ6BZcWEFbeVug==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
