---
id: linkedinbridge
url: http://mautrix-linkedin.matrix.svc.cluster.local:8000
as_token: "{{ .LINKEDIN_AS_TOKEN }}"
hs_token: "{{ .LINKEDIN_HS_TOKEN }}"
sender_localpart: "{{ .LINKEDIN_SENDER_LOCAL_PART }}"
rate_limited: false
namespaces:
  users:
    - regex: ^@linkedinbridge:${SECRET_DOMAIN//./\\.}$
      exclusive: true
    - regex: ^@linkedinbridge_.*:${SECRET_DOMAIN//./\\.}$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
