apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:ZLOrDjTvgCg9JtXwVTfq,iv:r3150nkvVDiU+mbLciinn2JOKP25ZFCuwc5AkIKPtG8=,tag:kuxxdnp72b4eee0i+ilcMA==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:j57ITGhK3EVuYXSbATaIQA==,iv:RKmUeNVspt69ValhA+iZLu9l8svKEpYgkfQTSNY196U=,tag:jih/MUM2P+BrOHWDOxfpfw==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:/KIyuPx9IB4CiQ==,iv:WE+U0eVXYninAt5MeIqXKUEjh1wrPHehAZo44wwq2Ss=,tag:dlWOoY7iHJ5t6TlhvNM0CQ==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:/MtZg8ZknbWtAhahfpM/,iv:vEymHatmw2/J51+zmy1v6DmOi8thlmFjJya8PtJTHiQ=,tag:+Q9W4lPXOvejYZVjIMdflw==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:mEQQk1P3ybG1Og==,iv:0pdl+eyQnUWw9ouDrShgmmlSKQmQx5hQHK39tT7cCZE=,tag:AcQSP+9MK3uRQY/us7cUiQ==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:7faD8NBQTY19AooMRuMeBao/FsdRSzsU5z2HZaY=,iv:fDuP7wm4WBc4ZNeYSFBnJ211IAdPg5Fi/Wh328Bd1pE=,tag:4/TQS30y+XT38VRcQvqEww==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:cIEgicX1o5xezRDKNSfbgw==,iv:tSV7PDpmD3/ad4qKopjNWAuBGsbKIl+B9Q1q3hoNmLE=,tag:kQnZlyts6xXF2HycDF35fQ==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbmYvZWlYOGd4dDhLWU1t
        dEtKdk13U1hycWlETmNJdWc5TWVlUHkvcFZNCm9WVytISjd2YTlNSTZDamVvRzNl
        bHRkZmdpUXpiZmEvMG5vMk53VWNJY2cKLS0tIEk0WlhFM09IT2hqTm5mdUdVQnVY
        MDlsdmtidVcyZ0pBWXR5R0lYTVdTaHcK5jYD4MZM+2YkklLNN6fkq+Z3wnFUiyJZ
        odk9940H+KeG3WHrpBn6ArfYPDG249ZtN9jEx/K9VSwCtHHUZx78rQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-27T00:19:37Z"
  mac: ENC[AES256_GCM,data:l7R+dAagPO0bXzJe7icN9gzqQOuV2uqowSCRqX7YOSfDtDHG/pYZ1HxFSaFuF8XioG6MepeJNk9jFGKlJHdVun3rlpZwW+gzHVQ4fAhb7byQmZEguO07SqbuudbeCJut9WTDJv7VkDaMRNNcQMflHQGKuxO9/oFbfdy3Tm6nfWM=,iv:6LjD6fxORCGcV1r1PjOtUHvr0X9L7GU3PEwwv3L+HIE=,tag:p6zd45QxiDClbfYL16a0Pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
