apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:XkCoV98SpGCT7ChvTd1+,iv:n8aEgoVNpapU528njkoniuLV1ReoVV16T/YIPnxIY8g=,tag:rjyEz17Eo/mAOcdw2Awgrw==,type:str]
  SECRET_ADMIN_EMAIL: ENC[AES256_GCM,data:HbkN/BnWzK0o4FjstjBzoA==,iv:rXpjTGI8ZJ13ljKj2nB5dkuHnTYrYCV5ONqI5H+BDbo=,tag:6K3eXYBiVkvIgFguBqWZDg==,type:str]
  SECRET_EXTERNAL_DOMAIN: ENC[AES256_GCM,data:KQzqvlKHWu5GVA==,iv:gj9x+W0JsUHNDrJhw5VlGpPFkk+aCr7NAxvcVWWHFPI=,tag:hiM50uobh1yfbl/5HzR3Lg==,type:str]
  SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:J2K5nNVwYX5VAW6VIFK+,iv:6iFDWUHrAHyJu1GFs8I0p87iI86BaIcdf/9QvFByGMM=,tag:c9eGNT1Hmfgkz7SQiBn6tg==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:ehLMIyO50ZZQVg==,iv:BrNUvX0Ll99pIk0bCmZHh0FNbKPmMSgVbg5yX01yUxQ=,tag:m2U6fjmKoZExZM7INAk5jA==,type:str]
  SECRET_SMTP_FROM: ENC[AES256_GCM,data:Y90OuOhU2JbhLZ2DQGhgU/vRy58oBGGeZuihsvk=,iv:by/MJz4WdBfbL5i9sypmtBXZLIToujgrwkFUS9JYKdg=,tag:CZJNMKT599ky0KtLMFq62g==,type:str]
  SECRET_SMTP_HOST: ENC[AES256_GCM,data:DN93fQBMHq4Zo7G2TM+CaA==,iv:qstFvrwtzMjjXTEZlaYsSIGgHMEcl2LSjC0dFhutgy0=,tag:9dxXQIE+u+PaTuTlWThC0A==,type:str]
  CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:6EXzexIIrv0n8tmoWj5t4N4RThdpuKFm+lDVLo1S+66/eKbO,iv:FN9BnDBvF10+x2AKXCsfEN2zY8prRXWpF1i83/u88ao=,tag:WPrsRR5H4gc9gky5m+tS3w==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSRTJwclV0OWU1Z0hCSG16
        OCtuSEVXWlFkbFJ0K3ZWRUsycnA1YzBBbXdjCkU4QjRjRnc2WTgrSHRNRkpjOXZ2
        S2E0eEpuTGV0cW56SDFZa1NkeWM5ckkKLS0tIHRFZ1AxOVR0RHRmayszMUNCN1p3
        dHlwb0x0U3BLTE1FdXNKZGs0bnUwTWMKyODgJWjpS8uwoSEhEZA4jqbJAEk/uKnQ
        CK10kbCkMo3m7uwCP3R/u3/5utLTQzHEOvJlz6zYjcpJHNsExac2/g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-03T17:26:31Z"
  mac: ENC[AES256_GCM,data:k+TzTeO2MJ7e0We+Y34+wkr8OhfR3IJQKYRazpqCTwXPOqmvnrlUDVRMoHZSZFbNsjjXjD/cmZYVttKRrzvG4MpR9D5V8FpJl44Itnk6nVWmHEk7mItOSYpNjmr7fewgUQwOlfaTvWsz+1bYx8c9XZ7GLfsckFD4Bj6PRm2g154=,iv:r92UME3Yk3IK29oC2Vx/8WCUOJJPBHGLkerhqNxzTtc=,tag:Qj/VnHfofq8uBLT+Lb+l9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
