---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./networkpolicy.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: element-configmap
    files:
      - config.json=./resources/config.json
generatorOptions:
  disableNameSuffixHash: true
