---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app mautrix-twitter
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-matrix
  target:
    name: mautrix-twitter-secret
    template:
      engineVersion: v2
      data:
        MAUTRIX_TWITTER_POSTGRES_DB: "{{ .MAUTRIX_TWITTER_POSTGRES_DB }}"
        MAUTRIX_TWITTER_POSTGRES_USER: "{{ .MAUTRIX_TWITTER_POSTGRES_USER }}"
        MAUTRIX_TWITTER_POSTGRES_PASSWORD: "{{ .MAUTRIX_TWITTER_POSTGRES_PASSWORD }}"
      templateFrom:
        - configMap:
            name: "mautrix-twitter-configmap"
            items:
              - key: config.yaml
        - configMap:
            name: "mautrix-twitter-configmap"
            items:
              - key: registration.yaml
  data:
    - secretKey: MAUTRIX_TWITTER_POSTGRES_USER
      remoteRef:
        key: "e81a7e64-6616-4503-89be-b3c5003806b7"
    - secretKey: MAUTRIX_TWITTER_POSTGRES_PASSWORD
      remoteRef:
        key: "792663df-caef-4758-808b-b3c5003813a7"
    - secretKey: MAUTRIX_TWITTER_POSTGRES_DB
      remoteRef:
        key: "a15e8ca8-0c5c-479c-9d7c-b3c50038200e"
    - secretKey: TWITTER_AS_TOKEN
      remoteRef:
        key: "efdc5356-1429-4b61-b427-b3c5003851d4"
    - secretKey: TWITTER_HS_TOKEN
      remoteRef:
        key: "97da4e87-f982-48c4-bb8e-b3c500385b5f"
    - secretKey: TWITTER_SENDER_LOCAL_PART
      remoteRef:
        key: "081d2396-a353-490d-993c-b3c500387e68"
    - secretKey: DISCORD_DOUBLE_PUPPET_AS_TOKEN
      remoteRef:
        key: "0b74846e-7a46-4c0b-866a-b3c0000123ad"
    - secretKey: DISCORD_DOUBLE_PUPPET_HS_TOKEN
      remoteRef:
        key: "5e64a842-2685-4293-86fb-b3c00001e7b1"
    - secretKey: DISCORD_DOUBLE_PUPPET_LOCAL_PART
      remoteRef:
        key: "43979b54-8b8e-4a7f-a8d6-b3c000039d41"
