# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-twitter-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:iW0MeKjtLGUdx2oPPkTLhjoQjV+6m8lONBkQ0gIAa2+pNmdewPEndA==,iv:z2Tk0JU4SGlFuhKejbpAvT5pIVtrTNy1a1/JaGNyxCI=,tag:fSqTipsewH+Ea3OmSjErkQ==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:lZIIonFL49BfI7HiOaN+,iv:rTC+CPjkqH2oW/FmYHComjp+p87TtgsIW1aIUViZzWM=,tag:EN8TYGG0vHzl747lNXY8wQ==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:cFdj7mngy3zauZLQKzbF,iv:jkVqp1qKkwseSwyuWsazc3HGEhIMdsS+QUjU5J6RdfE=,tag:8DsCFGkn5DaVvGNq8atZxA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:M4rXV2s8MA5yIpq7eTny9jSMUILzxbLw/pOjbQLDZ3BOxHZBMQy1gOLoEXRKD9h6yLprh7vLOCSOdHWtf1FqLQ==,iv:R/bxqwW54UpNuewiMZdDldoxuYgEVh8D/oDy/3G9+z8=,tag:Y6hZeUJSaC6ewudnutDNIw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTL29yQStDRmxzcHpLSWg1
        b0dGWTFSNVhrN0NTbXVVZ0FmRWJIc0pGaFhjCktWVjl0NTNoVVRxRG93L3UvcjBt
        V1VoWjJETFpWVWswWlY2SmRBa05pV3cKLS0tIEViMFg1UEJ1cVI4WjJZSDI4UGVo
        ckM1TUtnRzFBV09hSHJUWVorcW13THMKGvvVQiRExrgCHxME+3TwySffoSlThzTT
        /BnACYOTT5W93+VqYo+u1yOkrLpe0IYkfPDRss3IDttZKOcdug6MAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-01T20:40:38Z"
  mac: ENC[AES256_GCM,data:riIP6DkEQkiDc03wKS5QW88n7mQax2B1cKD9yOpMim5y7vVNMht+yNkHCFz85wv9+eEO6WMUjvVoK/nXiwPKJ1VSpBdIkXGeqMJ9BJ+JgIHfN/jWs71X5PVaJFp6d6+GLnlpo5J+Ldsll0Pv89L/2apznkG8KMFmCRHhGnDxEyI=,iv:xWhJrHigNas1eE9OkdfySkt8fJK02FSgIh3r1TKG9yY=,tag:wO0b0Gcp7hgSplLjTjalBQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
