---
id: signalbridge
url: http://mautrix-signal.matrix.svc.cluster.local:8000
as_token: "{{ .SIGNAL_AS_TOKEN }}"
hs_token: "{{ .SIGNAL_HS_TOKEN }}"
sender_localpart: "{{ .SIGNAL_SENDER_LOCAL_PART }}"
rate_limited: false
namespaces:
  users:
    - regex: ^@signalbridge:${SECRET_DOMAIN//./\\.}$
      exclusive: true
    - regex: ^@signalbridge_.*:${SECRET_DOMAIN//./\\.}$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
