---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: anubis
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: anubis-secret
    template:
      data:
        ED25519_PRIVATE_KEY_HEX: "{{ .ANUBIS_KEY }}"
  data:
    - secretKey: ANUBIS_KEY
      remoteRef:
        key: "4d20f206-75b4-471e-a3bb-b3c70104f4db"
