---
id: discordbridge
url: http://mautrix-discord.matrix.svc.cluster.local:8000
as_token: "{{ .AS_TOKEN }}"
hs_token: "{{ .HS_TOKEN }}"
sender_localpart: "{{ .SENDER_LOCAL_PART }}"
rate_limited: false
namespaces:
  users:
    - regex: ^@discordbridge:${SECRET_EXTERNAL_DOMAIN//./\\.}$
      exclusive: true
    - regex: ^@discordbridge_.*:${SECRET_EXTERNAL_DOMAIN//./\\.}$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
