---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: lldap-secret
    template:
      engineVersion: v2
      data:
        LLDAP_JWT_SECRET: "{{ .LLDAP_JWT_SECRET }}"
        LLDAP_KEY_SEED: "{{ .LLDAP_KEY_SEED }}"
        LLDAP_LDAP_USER_PASS: "{{ .LLDAP_LDAP_USER_PASS }}"
        LLDAP_LLDAP_USER_DN: "{{ .LLDAP_LLDAP_USER_DN }}"
        LLDAP_LDAP_USER_EMAIL: "{{ .LLDAP_LDAP_USER_EMAIL }}"
        LLDAP_SERVER_KEY_SEED: "{{ .LLDAP_SERVER_KEY_SEED }}"
        LLDAP_POSTGRES_DB: "{{ .LLDAP_POSTGRES_DB }}"
        LLDAP_POSTGRES_USER: "{{ .LLDAP_POSTGRES_USER }}"
        LLDAP_POSTGRES_PASSWORD: "{{ .LLDAP_POSTGRES_PASSWORD }}"
  data:
    - secretKey: LLDAP_POSTGRES_DB
      remoteRef:
        key: "c09e2365-fdc4-47c0-803f-b3d50167bf6f"
    - secretKey: LLDAP_POSTGRES_USER
      remoteRef:
        key: "90cd7d2c-6b1d-49db-9911-b3d50167cf8f"
    - secretKey: LLDAP_POSTGRES_PASSWORD
      remoteRef:
        key: "3c71867e-f081-47c7-a2cb-b3d50167f165"
    - secretKey: LLDAP_LDAP_USER_PASS
      remoteRef:
        key: "cad868eb-8b23-4345-b272-b3d600146e3d"
    - secretKey: LLDAP_LLDAP_USER_DN
      remoteRef:
        key: "5752adb3-faa4-45e7-a2b4-b3d6001462d5"
    - secretKey: LLDAP_LDAP_USER_EMAIL
      remoteRef:
        key: "2cefaa7b-c83f-4182-a799-b3d600145771"
    - secretKey: LLDAP_SERVER_KEY_SEED
      remoteRef:
        key: "a657b21a-6f57-44f3-80cf-b3d60014efb6"
    - secretKey: LLDAP_JWT_SECRET
      remoteRef:
        key: "aa4d4f99-0f22-49f7-b967-b3d6000f47a4"
    - secretKey: LLDAP_KEY_SEED
      remoteRef:
        key: "96467520-6a47-4e7f-bdd8-b3d6000f5288"
