---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./networkpolicy.yaml
  - ./namespace.yaml
  - ./synapse/ks.yaml
  - ./synapse-admin/ks.yaml
  - ./element/ks.yaml
  - ./mautrix-discord/ks.yaml
  - ./mautrix-meta/ks.yaml
  - ./mautrix-linkedin/ks.yaml
  - ./mautrix-twitter/ks.yaml
  - ./mautrix-signal/ks.yaml
