---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &app mautrix-meta
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    name: mautrix-meta-secret
    template:
      engineVersion: v2
      templateFrom:
        - configMap:
            name: "mautrix-meta-configmap"
            items:
              - key: config.yaml
        - configMap:
            name: "mautrix-meta-configmap"
            items:
              - key: registration.yaml
  data:
    - secretKey: SECRET_DOMAIN
      remoteRef:
        key: "336bff2a-c389-4307-bacc-b3bf016ee8d6"
    - secretKey: MAUTRIX_META_POSTGRES_USER
      remoteRef:
        key: "aafa913d-3e2c-451e-912f-b3c2000fe8c1"
    - secretKey: MAUTRIX_META_POSTGRES_PASSWORD
      remoteRef:
        key: "100f8f28-dacc-42ec-ba90-b3c2001014a6"
    - secretKey: MAUTRIX_META_POSTGRES_DB
      remoteRef:
        key: "0fd9a202-15fc-4d13-a91d-b3c200103578"
    - secretKey: META_AS_TOKEN
      remoteRef:
        key: "b358ab46-68b1-4e55-9b18-b3c200104eeb"
    - secretKey: META_HS_TOKEN
      remoteRef:
        key: "4671ebeb-5f50-4606-9a5c-b3c200106537"
    - secretKey: META_SENDER_LOCAL_PART
      remoteRef:
        key: "2ddfcd2f-87b9-48c3-bb3b-b3c20010a028"
    - secretKey: DISCORD_DOUBLE_PUPPET_AS_TOKEN
      remoteRef:
        key: "0b74846e-7a46-4c0b-866a-b3c0000123ad"
    - secretKey: DISCORD_DOUBLE_PUPPET_HS_TOKEN
      remoteRef:
        key: "5e64a842-2685-4293-86fb-b3c00001e7b1"
    - secretKey: DISCORD_DOUBLE_PUPPET_LOCAL_PART
      remoteRef:
        key: "43979b54-8b8e-4a7f-a8d6-b3c000039d41"
