# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-meta-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8UfNdHKcYlyWOVgLV5L2Ai6HY/FSEej+yreSND6wAHdNbvrmIixNUg==,iv:WYoWU9Bw3DK9f+UlJH0xchACZ/G4p4zhhx8jDoo21o8=,tag:9NL7DnBjKOC7+696HFBY8g==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Gwpek0ZBs2U4CXlo,iv:mPI3zrkIJSDOeZiciZq0P64IbLjQFvsC4P1+2925LvU=,tag:iOlayjgpVxtmP242mFo72A==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:h3+Xg6NufywNKbbI,iv:exzYkZ9M5/QQtSOO8k9DpxkPUWk+jAuCyat9t0kmliw=,tag:eaFN4M0SbiSEQZxb8Yvt6A==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:tBJGwqI8Q4XTd6MYxYsJjdeGD18hNJkxXJJlBMh2efUB4xXRVXjenfPX2V/gISzDH9IM1SkoVx2yYPlNwD7Dgw==,iv:gDwz2xgHIAuO+Yg47qbx6sXSwiGSz5WvKFWk2TktcMA=,tag:Y+m6V6+wH5Lja5yVN1GvYQ==,type:str]
  INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:YXYXIRVrkioEzgYjuWIne5qEPMliFZ6Wc1J+3g==,iv:Ii/Vz7KT91+XCbOtFNgFJE6rwS27C51kT2QXB4KqPFo=,tag:YpDnH/QjnrakXpkIJtebPg==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhZmE3MG5UWkdOVDBGejdH
        NVRHY0FTSnQwbndKU3RxT083YnBvMGxXL1dvCmI4YzJiMlJuc0hXeEpaYzRDb1J0
        L2lUZ1h4WVlyc2hKNkJONHhVSUlZQ3MKLS0tIGd2bnBqamxxdnd3RDl4Uy9XZ1Z1
        RkxFb21vclhDRmE2TDk1UWdNMmc0cWcKBjeAa94ETcYFlY3yg2GMI/hn0LSBqwHz
        T/8gKHqm7TwsmCiwh1eYD+XKBAgSytZ1HwGiikxn04J2ADPMOSYISw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-29T01:02:14Z"
  mac: ENC[AES256_GCM,data:6t9QTKFPwjYnM+GJmhP2unTFAZw3H3PxvadRTtiU8CQ98/txRHQocJvuApEFF2mfQ1xR5rkNiMBIsYpw8EFGeu73ZrUk1SgPo9UHfqKVt9QXCO1m61/ichvYRZuSjhYESNbjTX5YI/rvJROI1G4kZcZn5iq0IJpv1b9IlCHZpKw=,iv:6vjfE51T8ZMAu5gtt9vmCi094BrFGoIsx67fZoG3Qsg=,tag:qxY+zjFM8/OftWc0QRr/nA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
