# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: mautrix-meta-db-secret
stringData:
  INIT_POSTGRES_HOST: ENC[AES256_GCM,data:gW14L/6LjMIiu5283wALsjKS+xYKUndTDiJlYFV7Rh/5p+oMd35kdg==,iv:aAM7vBjuxgz/g9yEXYiClGSKjpBK2n9dq9OnNeeK9xM=,tag:n0KQ1RCegnCYhhh4CAA/jA==,type:str]
  INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:nqx66xZPNTmjLwPW,iv:/NGkY/N3psVuUiy+ViLxRlFJ3VC1C46K9IG9ZBee0vk=,tag:8vtFrhCk29c3NmVbndVfGg==,type:str]
  INIT_POSTGRES_USER: ENC[AES256_GCM,data:gWWttW8XjNsqvqGU,iv:Z6Twjos4+N7TswIclmwNYTkYzHJQnW0kdbwGH7Ou4lw=,tag:pxAIamQl6Lc0Jj17JPWqwA==,type:str]
  INIT_POSTGRES_PASS: ENC[AES256_GCM,data:D+gFk/5NRbSUvuJ1j3ZRUFoQJRPO4iEt5w54oSjri8tuIPCXVRf7U7LnGVZ2MZYntXsVoY1uX2frjeew3EI5zA==,iv:FmOJn4M8kCNplks20zfvSC/q5c9N5juCwob3M5r4lwA=,tag:PBOTqbcV3dx43DB6AGtPIw==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtSVhCR0xSYVVkVUVoV2la
        a1owNWdQK0RmbnpKaDg4WEZqc0hYNi8xa0cwCmdWS0xWbkNuZTRway92M2hUSEV4
        QnkwWDNrY1djS1lrK3ZSSmlIN1B0OFkKLS0tIFoxdVN4WmtQV1kxVlVKWHZnbWlk
        NTRUZGU5a043T3lXYW9PUWluVEFjODgK6paK30U4qormF6duGUj8UykbFZz9J7IY
        h+HLX+V9Qj8nYIh/gKqCKL7uLaWInckBDVN8Ss8oNAhLj9oasbPkjA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-31T23:03:27Z"
  mac: ENC[AES256_GCM,data:ixJwyx2Yx5+wqwYwaMqoUwbYhgyWT6dEsxsz+y+E2s+23Z+gJQXye6sfgeAabVSIi15y8FG8KNG2Bfoqz+q2iXgIakG2U1YnpaC3ePiPP34KO/0q05oTYxV1qMai+KjgtZoKcalFHXxS40AewfZtlyYDNETQ3BFAZaFVLZWA5FU=,iv:sqyl9aOZrkIFP4jSmdFMZWdjTuy41ubpKMEsY0oguTA=,tag:TRXTWpXG5snr3n8y/RIlrA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
