# yamllint disable
kind: Secret
apiVersion: v1
type: Opaque
metadata:
  name: minecraft-secret
stringData:
  OPS: ENC[AES256_GCM,data:d7wEg5C1,iv:+UP+cDIitMSimISKc62B9ItHqQ5bpGcx6l9QxhV1Emo=,tag:Zd67ImLLpnwGN0P0YIBxYw==,type:str]
  WHITELIST: ENC[AES256_GCM,data:B5bOJ41G,iv:mGmEgc1C09dexG6zLEDlfJN088/elmphdd6ryK7OyXQ=,tag:NngpbmQZ3rM0FBtUjhkReA==,type:str]
  CF_API_KEY: ENC[AES256_GCM,data:d0Tp5PsaM+FprNdlC3fpfw91OQtyd40Tp8AoKz+V/7h0dTQKFQXgI36kEJa6AObCoHgVD7CLN+ngyWVw,iv:0DXimAex9DBKJhH6ZdW1psuDB26n5y+Dm0EYGJ0BgCc=,tag:bwJS+vB4091k16bRd1QUmQ==,type:str]
sops:
  age:
    - recipient: age1zmrywhk3kp7490q25eua25rlx4zg9wu97fc64ahdm65zv3dv39psetsa4u
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcmM4ZndzUEplWXNMUEM2
        OVJiZzNFRXpGb0VidC9ucVlGNHVEZkVOWFFBCnpraDBPc3VkVjZ4V0x0K1VHYWll
        bWtkSWViSi9sUy92U3lWdHYvWHQ3TjgKLS0tIFNkd2d3VXdqSWVIeEJQbk9FbHNj
        NEx5ckFkK1VraXFHOWFNeUVTMjFuNjQKXlsnV1xp2806sxHrg1gEbmlYbCvAqyq6
        rYamQmUrcwLsiDMMiM91SMGiChh0yUGH9vJydPN0IYnRaasKnmj4UA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-18T00:40:36Z"
  mac: ENC[AES256_GCM,data:ZxyCRRrxPCqW5Y8254hBlG28u72o7HH7xMgCCGHy8MUdKcYA+kH54hkVURsNG7p4x3szUX3JwodfedDzASS8HnQwy5Tl2aYzk6iAT4S+5w2CALx0UAmnbiuOXEvltbPjKOcqexcE5sDZdhXeRUqB3TnIniH5nI2l+QCujRUhJjU=,iv:JB3zWQ0wCMhxAOZDwFK+TTc4npM4VloOr2PxWWJASTo=,tag:E3ooTk27Xw23RyKfIk5rLA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
