---
id: metabridge
url: http://mautrix-meta.matrix.svc.cluster.local:8000
as_token: "{{ .META_AS_TOKEN }}"
hs_token: "{{ .META_HS_TOKEN }}"
sender_localpart: "{{ .META_SENDER_LOCAL_PART }}"
rate_limited: false
namespaces:
  users:
    - regex: ^@metabridge:${SECRET_DOMAIN//./\\.}$
      exclusive: true
    - regex: ^@metabridge_.*:${SECRET_DOMAIN//./\\.}$
      exclusive: true
de.sorunome.msc2409.push_ephemeral: true
receive_ephemeral: true
