---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-anubis
spec:
  forwardAuth:
    address: http://anubis.security.svc.cluster.local:8080/.within.website/x/cmd/anubis/api/check
