---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-auth-anubis
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
      - name: networking-traefik-middleware-anubis@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-no-compress
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-authentik
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-shlink
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers-shlink@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-chain-synapse
spec:
  chain:
    middlewares:
      - name: networking-traefik-middleware-secure-headers-synapse@kubernetescrd
      - name: networking-traefik-middleware-compress@kubernetescrd
