---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-secure-headers
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
    accessControlMaxAge: 100
    accessControlAllowOriginListRegex:
      - "https://(.*?)${SECRET_EXTERNAL_DOMAIN}"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-For"
      - "X-Forwarded-Proto"
      - "X-GEO-City"
      - "Cf-Connecting-Ip"
      - "Cf-Ipcountry"
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    customFrameOptionsValue: "allow-from https:${SECRET_DOMAIN}"
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: "strict-origin-when-cross-origin"
    contentSecurityPolicy: "upgrade-insecure-requests;"
    customResponseHeaders:
      Permissions-Policy: >-
        accelerometer=(),
        camera=(),
        geolocation=(),
        gyroscope=(),
        magnetometer=(),
        microphone=(),
        payment=(),
        usb=()
      Cross-Origin-Opener-Policy: same-origin
      Cross-Origin-Resource-Policy: same-origin
      Cross-Origin-Embedder-Policy: require-corp
      X-Frame-Options: "SAMEORIGIN"
      X-Robots-Tag: "noindex,nofollow,noarchive,nosnippet,notranslate,noimageindex"
      X-Permitted-Cross-Domain-Policies: "none"
      X-Forwarded-Proto: "https"
      City: X-GEO-City
      X-Powered-By: ""
      server: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-secure-headers-hugo
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
    accessControlMaxAge: 100
    accessControlAllowOriginListRegex:
      - "https://(.*?)${SECRET_DOMAIN}"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-For"
      - "X-Forwarded-Proto"
      - "X-GEO-City"
      - "Cf-Connecting-Ip"
      - "Cf-Ipcountry"
    stsSeconds: 31536000
    stsIncludeSubdomains: true
    stsPreload: true
    forceSTSHeader: true
    customFrameOptionsValue: "allow-from https:${SECRET_DOMAIN}"
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: "strict-origin-when-cross-origin"
    contentSecurityPolicy: >-
      default-src 'none';
      script-src 'self';
      style-src 'self';
      img-src 'self';
      font-src 'self';
      form-action 'none';
      frame-ancestors 'none';
      base-uri 'self';
      upgrade-insecure-requests
    customResponseHeaders:
      Permissions-Policy: >-
        accelerometer=(),
        camera=(),
        geolocation=(),
        gyroscope=(),
        magnetometer=(),
        microphone=(),
        payment=(),
        usb=()
      Cross-Origin-Opener-Policy: same-origin
      Cross-Origin-Resource-Policy: same-origin
      Cross-Origin-Embedder-Policy: require-corp
      X-Frame-Options: "SAMEORIGIN"
      X-Robots-Tag: "index, follow"
      X-Permitted-Cross-Domain-Policies: "none"
      X-Forwarded-Proto: "https"
      City: X-GEO-City
      X-Powered-By: ""
      server: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-secure-headers-shlink
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - OPTIONS
      - PUT
      - POST
      - DELETE
    accessControlMaxAge: 100
    accessControlAllowOriginListRegex:
      - "https://(.*?)${SECRET_DOMAIN}"
    accessControlAllowHeaders:
      - "Content-Type"
      - "X-API-Key"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-For"
      - "X-Forwarded-Proto"
      - "X-GEO-City"
      - "Cf-Connecting-Ip"
      - "Cf-Ipcountry"
    stsSeconds: 31536000
    stsIncludeSubdomains: false
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    frameDeny: true
    referrerPolicy: "same-origin"
    contentSecurityPolicy: "upgrade-insecure-requests;"
    customResponseHeaders:
      Permissions-Policy: >-
        accelerometer=(),
        camera=(),
        geolocation=(),
        gyroscope=(),
        magnetometer=(),
        microphone=(),
        payment=(),
        usb=()
      X-Frame-Options: "SAMEORIGIN"
      X-Robots-Tag: "noindex,nofollow,noarchive,nosnippet,notranslate,noimageindex"
      X-Permitted-Cross-Domain-Policies: "none"
      X-Forwarded-Proto: "https"
      City: X-GEO-City
      X-Powered-By: ""
      server: ""
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: traefik-middleware-secure-headers-synapse
spec:
  headers:
    accessControlAllowMethods:
      - GET
      - PUT
      - POST
      - OPTIONS
      - DELETE
    accessControlMaxAge: 3600
    accessControlAllowOriginListRegex:
      - "https://(.*?)${SECRET_DOMAIN}"
      - "element://.*"
      - "vector://.*"
      - "http://localhost"
    accessControlAllowHeaders:
      - "Accept"
      - "Authorization"
      - "Content-Type"
      - "Origin"
    hostsProxyHeaders:
      - "X-Forwarded-Host"
      - "X-Forwarded-For"
      - "X-Forwarded-Proto"
      - "X-GEO-City"
      - "Cf-Connecting-Ip"
      - "Cf-Ipcountry"
    stsSeconds: 31536000
    stsIncludeSubdomains: false
    stsPreload: true
    forceSTSHeader: true
    contentTypeNosniff: true
    frameDeny: true
    accessControlAllowCredentials: true
    addVaryHeader: true
    referrerPolicy: "same-origin"
    contentSecurityPolicy: "upgrade-insecure-requests;"
    customResponseHeaders:
      Permissions-Policy: >-
        accelerometer=(),
        camera=(),
        geolocation=(),
        gyroscope=(),
        magnetometer=(),
        microphone=(),
        payment=(),
        usb=()
      X-Frame-Options: "SAMEORIGIN"
      X-Robots-Tag: "noindex,nofollow,noarchive,nosnippet,notranslate,noimageindex"
      X-Permitted-Cross-Domain-Policies: "none"
      X-Forwarded-Proto: "https"
      City: X-GEO-City
      X-Powered-By: ""
      server: ""
