---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: mautrix-signal-configmap
    files:
      - config.yaml=./resources/config.yaml
      - registration.yaml=./resources/registration.yaml
generatorOptions:
  disableNameSuffixHash: true
