---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clustersecretstore_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
  namespace: external-secrets
spec:
  provider:
    bitwardensecretsmanager:
      apiURL: https://vault.bitwarden.com/api
      identityURL: https://vault.bitwarden.com/identity
      bitwardenServerSDKURL: https://bitwarden-sdk-server.external-secrets.svc.cluster.local:9998
      auth:
        secretRef:
          credentials:
            key: token
            name: bitwarden-secret-token
            namespace: external-secrets
      caProvider:
        type: Secret
        name: bitwarden-tls-certs
        namespace: cert-manager
        key: ca.crt
      organizationID: 22b58a43-d6a5-4952-8d39-b3bf011b72bd
      projectID: c2f844ee-a1cb-4e0b-9410-b3bf011ba30b
